apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::ACCOUNT_ID:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-17T16:56:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "848"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 37091677-a936-416a-8318-161f5cf9b50d
