apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::619611021436:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AWCVQ06KRGCA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::619611021436:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-17T16:56:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7224"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 37091677-a936-416a-8318-161f5cf9b50d
